version: '2'

services:

  web:
    image: wordpress
    ports:
      - 8282:80
    environment:
      WORDPRESS_DB_PASSWORD: password
      VIRTUAL_HOST: localhost.xip.io
      LETSENCRYPT_HOST: 10.1.6.113.xip.io
      LETSENCRYPT_EMAIL: rsperoni@mgcoders.com
    links:
      - mysql
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress

networks:
  default:
    external:
      name: nginx-proxy

