version: '3.1'

services:

  web:
    image: wordpress
    ports:
      - 8282:80
    environment:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_NAME:
      VIRTUAL_HOST:

   volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads

networks:
  default:
    external:
      name: nginx-proxy

