version: '3.1'

services:

  web:
    image: wordpress
    ports:
      - 8282:80
    environment:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_NAME:
      VIRTUAL_HOST:

   volumes:
     - ./wp-content:/var/www/html/wp-content

networks:
  default:
    external:
      name: nginx-proxy

