version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1000:80"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_PASSWORD: 
      PMA_HOST:
      VIRTUAL_HOST:

networks:
  default:
    external:
      name: nginx-proxy

